APPS/Models/APPS.cs
namespace AppsServices.Models
{
    public class APPS
    {
        public int AppID { get; set; }
        public string AppName { get; set; } = string.Empty;
        public int Ratings { get; set; }
        public string info { get; set; } = string.Empty;
        public string Link { get; set; } = string.Empty;

        public string Response { get; set; } = string.Empty;

    }
}

APPS/Models/AllModels.cs
namespace AppsServices.Models
{
    public class AllModels
    {
        public APPS? APPS { get; set; }
        public List<APPS>? APPSList { get; set; }

    }
}

APPS/Models/ErrorViewModel.cs
namespace AppsServices.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

APPS/Models/Login.cs
namespace AppsServices.Models
{
    public class login
    {
        public string AdminName { get; set; }
        public string Password { get; set; }
    }
}

APPS/Controllers/APPSController.cs
using AppsServices.Models;
using AppsServices.Services;
using Microsoft.AspNetCore.Mvc;
using System.Configuration.Provider;

namespace AppsServices.Controllers
{
    public class APPSController : Controller
    {
        
        private readonly IConfiguration _configuration;
        private readonly IAPPSService _aPPSService;
        public APPSController(IConfiguration configuration, IAPPSService APPSService)
        {
            _configuration = configuration;
            _aPPSService= APPSService;
        }
        //Action metodu controller'dan gelen bilgiyi alır işler ve sonuç olarak kullanıcıya bir Http Response döndürür. 
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult APPSList()
        {
            AllModels model = new AllModels();

             model.APPSList = _aPPSService.GetAPPSList().ToList();

            return View(model);
        }



        [HttpPost]
        public IActionResult InsertUpdateAPPSRecord(APPS formData)
        {
            AllModels model = new AllModels();

            string url = Request.Headers["Referer"].ToString();
            string resault = String.Empty;

            if (formData.AppID > 0)
            {
                resault = _aPPSService.UpdateAPPSRecord(formData);
            }
            else
            {
                resault = _aPPSService.InsertAPPS(formData);
            }

           
            if (resault == "recorded")
            {
                TempData["SuccessMsg"] = "recorded";
                return Redirect(url);
            }
            else
            {
                TempData["ErrorMsg"] = resault;
                return View(url);
            }
        }

        [HttpPost]
        public JsonResult DeleteAPPSRecord(int AppID)
        {
            
            string url = Request.Headers["Referer"].ToString();

            string resault = _aPPSService.DeleteAPPSRecord(AppID);
            if (resault == "DELETED")
            {
               
                return Json(new { message = "DELETED" });
            }
            else
            {
                
                return Json(new { message = "ERROR" });
            }
        }

    }
}

APPS/Controllers/HomeController.cs
using AppsServices.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppsServices.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

APPS/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using AppsServices.Models;


namespace AppsServices.Controllers
{


    public class LoginController : Controller
    {
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(login Login)
        {
            if (LoginUser(Login.AdminName, Login.Password))
            {
                var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, Login.AdminName)
            };

                var userIdentity = new ClaimsIdentity(claims, "login");

                ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);
                await HttpContext.SignInAsync(principal);

                //Just redirect to our index after logging in. 
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index");
        }

        private bool LoginUser(string AdminName, string Password)
        {
            if (AdminName == "admin" && Password == "123")
            {
                return true;
            }
            else
            {
                return false;
            }

        }
    }


}

APPS/Views/APPS/APPSList.cshtml
@model AppsServices.Models.AllModels

@{
    ViewData["Title"] = "home page";

}

<div class="text-center">
    <div class="row">

        <div class="col-lg-12" style="margin-top: 10px; margin-bottom: 10px" ;>
            @{
                if (TempData["SuccessMsg"] != null)
                {
                    <h3 style="background-color: pink;">@TempData["SuccessMsg"]</h3>
                }
            }
            @{
                if (TempData["ErrorMsg"] != null)
                {
                    <h3 style="background-color: red;">@TempData["ErrorMsg"]</h3>
                }
            }

        </div>

        <div class="col-lg-8 m-1" style="text-align: start;">
            <form method="post" asp-area="" asp-controller="APPS" asp-action="InsertUpdateAPPSRecord">
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <label for="AppName">AppName</label>
                    <input type="text" class="form-control" name=AppName id="AppName" placeholder="Enter App Name">
                    <input type="hidden" id="AppID" name="AppID">
                </div>
                <div class="form-group">
                    <label for="Ratings">Ratings</label>
                    <input type="number" class="form-control" name=ratings id="Ratings" placeholder="Raitings">
                </div>
                <div class="form-group">
                    <label for="info">info</label>
                    <input type="text" class="form-control" name=info id="info" placeholder="Enter description">

                </div>
                <div class="form-group" style="margin-bottom: 10px" ;>
                    <label for="Link">Link</label>
                    <input type="text" class="form-control" name=Link id="Link" placeholder="Enter Link">
                </div>

                <button type="submit" class="btn btn-primary">ADD APP</button>
                <br />
                <br />
            </form>

        </div>

        <div class="col-lg-12">
            <table class="table table-bordered">
                <thead class="thead-light">
                <thead>
                    <tr>
                        <th scope="col">AppID</th>
                        <th scope="col">AppName</th>
                        <th scope="col">Ratings</th>
                        <th scope="col">info</th>
                        <th scope="col">Link</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                        @{
                            if (Model.APPSList != null && Model.APPSList.Count > 0)
                            {
                                foreach (var item in Model.APPSList)
                                {
                                <tr>
                                    <td>@item.AppID</td>
                                    <td>@item.AppName</td>
                                    <td>@item.Ratings</td>
                                    <td>@item.info</td>
                                    <td>@item.Link</td>
                                    <td>
                                        <button class="btn btn-danger" style="width:100px" onclick="DeleteApp('@item.AppID')">Delete</button><br>
                                        <button class="btn btn-info" style="width:100px" onclick="UpdateAPPSRecord('@item.AppID','@item.AppName','@item.Ratings','@item.info','@item.Link')">Update</button>
                                    </td>
                                </tr>
                                }
                            }
                        }
                </tbody>
            </table>

        </div>

    </div>
</div>

<script>

    function DeleteApp(AppID) {
        let response = confirm("Do you realy want to delete this recod?");
        if (response) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("DeleteAPPSRecord","APPS")',
                data: { AppID: AppID },
                //contentType: "application/json; charset=utf-8",
                //dataType: "json",

                success: function (response) {

                    if (response.message == 'DELETED') {
                        window.location.reload();
                    }
                    else {
                        alert(response.message)
                    }
                },
                complete: function () {

                },
                failure: function (jqXHR, textStatus, errorThrown) {
                    alert("error. please try again.");
                }
            });
        }
    }

    function UpdateAPPSRecord(AppID, AppName, Ratings, info, Link) {

        $('#AppID').val(AppID);
        $('#AppName').val(AppName);
        $('#Ratings').val(Ratings);
        $('#info').val(info);
        $('#Link').val(Link);

    }

</script>

APPS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "home page";
    
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>
        <h5>FOR ADMİN</a></h5>
    </p>
</div>
<img src="https://www.apple.com/v/app-store/b/images/meta/og__c59t0pflacq6.png?202111230220" class="mx-auto d-block" alt="Responsive image">

APPS/Views/Login/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<header><link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true" /></header>
<div class="loginBox">
    <img class="user" src="https://i.ibb.co/yVGxFPR/2.png" height="100px" width="100px">
    <h3>Login</h3>
    <form action="/Home/Index" method="post">
        <div class="inputBox"> <input id="AdminName" type="text" name="AdminName" placeholder="Admin Name"> <input id="Password" type="password" name="Password" placeholder="Password"> </div> <input type="submit" name="" value="Login">
    </form>
    <a href="#">Forget Password<br> </a>
    <div class="text-center">
        <p style="color: #59238F;"></p>
    </div>

</div>

APPS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - APPS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/APPS.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">APPS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="APPS" asp-action="APPSList">APPSList</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - APPS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>